### ISSUE TITLE
数据库问题

### ISSUE THREAD

**Issue by blnp** [kiwifruit-guo/House_rental_system#1]
能求一份数据库的SQL命令吗

**Comment by kiwifruit-guo** [comment]
Happy to help you! I have uploaded a new folder named "sql", please take the database you need in the folder. If you have any questions, please feel free to contact me😀.

**Comment by kiwifruit-guo** [comment]
Happy to help you! I have uploaded a new folder named "sql", please take the database you need in the folder. If you have any questions, please feel free to contact me😀.



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年5月19日(周四) 下午4:38
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [kiwifruit-guo/House_rental_system] 数据库问题 (Issue #1)




 
能求一份数据库的SQL命令吗，在自己创建一个数据库后，发现需要一个house_info的表，没有实现项目，因此想要一份数据库表的SQL命令。

**Comment by blnp** [comment]
Thank you very much for your reply and your help




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "kiwifruit-guo/House_rental_system"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月19日(星期四) 晚上6:48
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [kiwifruit-guo/House_rental_system] 数据库问题 (Issue #1)





 Happy to help you! I have uploaded a new folder named "sql", please take the database you need in the folder. If you have any questions, please feel free to contact me😀. 
 
 
 
 ---原始邮件--- 
 发件人: ***@***.***&amp;gt; 
 发送时间: 2022年5月19日(周四) 下午4:38 
 收件人: ***@***.***&amp;gt;; 
 抄送: ***@***.***&amp;gt;; 
 主题: [kiwifruit-guo/House_rental_system] 数据库问题 (Issue #1) 
 
 
 
 
   
 能求一份数据库的SQL命令吗，在自己创建一个数据库后，发现需要一个house_info的表，没有实现项目，因此想要一份数据库表的SQL命令。

**Comment by blnp** [comment]
Thank you for your email, I have cloned this project




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "kiwifruit-guo/House_rental_system"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月22日(星期天) 晚上9:49
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [kiwifruit-guo/House_rental_system] 数据库问题 (Issue #1)





 
Closed #1 as completed.
